import { QuestionQuiz } from '../interfaces/question.interface';

export const QuestionQuizes: QuestionQuiz[] = [
  {
    timer: { seconds: 20 },
    title: 'Cocktails',
    questions: [
      'Tu te mets combien en Cocktails_?',
      '1. Le Pina Colada vient elle de Porto Rico ou de Thailande_?',
      '2. Quelle boisson alcoolisee iberique est a base de vin rouge sucre cannelle fruits et agrumes maceres_?',
      '3. Du Cosmopolitan Blue Lagoon Bloody Mary Daiquiri et Black Russian lequel n est pas a base de vodka_?',
      '4. Si des amis chics te demandent un Kir Royal quels ingredients utiliseras tu_?',
      '5. Comment s appelle le cocktail inspire de la Caipinrinha ou la cachaca est remplacee par de la vodka_?',
    ],
    answers: [
      '',
      'Porto Rico',
      'La Sangria',
      'La Daiquiri qui est a base de rhum',
      'Champagne et creme de cassis',
      'Caipiroska',
    ],
  },
  {
    timer: { seconds: 20 },
    title: 'Albums quebecois des annees 2000',
    questions: [
      'Tu te mets combien en Albums quebecois des annees 2000_?',
      '1. Il a produit cinq albums dans les annees 2000 dont La Vallee des reputations en 2002. Est ce Jean Lechien Jean Leloup ou Jean Lemulot_?',
      '2. Cet album de Mes Aieux lance en 2008 evoque quelle ligne du metro de Montreal dans son titre  verte rose bleu ou orange_? ',
      '3. Lequel de ces albums de Daniel Belanger n est pas paru dans les annees 2000  Rever mieux L Echec du materiel ou Les insomniaques s amusent',
      '4. Funeral est le titre de l album de 2004 de quel groupe montrealais qui allait quelques annees plus tard etre consacre aux Grammy Awards_?',
      '5. Trompe l oeil est le titre de quel groupe quebecois francophone ayant attire l attention du Canada anglophone et des Etats Unis_?',
    ],
    answers: [
      '',
      'Jean Leloup',
      'La ligne orange',
      'Les insomniaques s amusent',
      'The Arcade Fire',
      'Malajube',
    ],
  },
  {
    timer: { seconds: 20 },
    title: 'Vin rouges',
    questions: [
      'Tu te mets combien en Vin rouges_?',
      '1. Vin populaire en epicerie suis je le Kangaroo Red le Wallaroo Trail ou le Woowoo Rail_?',
      '2. Qu est ce qui evite l alteration du nectar dans le vin  le sulfite le sulfate ou le salsifis_?',
      '3. Si vous achetez un Orpaillaieur rouge de quel pays provient votre vin_?',
      '4. Quel cepage rouge est la specialite de la Californie_?',
      '5. Qu est ce que le mout_?',
    ],
    answers: [
      '',
      'Wallaroo Trail',
      'Le sulfite',
      'Canada',
      'Zinfandel',
      'Le jus de raison avant le processus de vinification',
    ],
  },
  {
    timer: { seconds: 20 },
    title: 'Bieres',
    questions: [
      'Tu te mets combien en Bieres_?',
      '1. Les sages femmes de La Tuque recommandent elles la consommation de biere pour les femmes enceintes de jumeaux roux_?',
      '2. Quelle micro brasserie quebecoise produit la Blanche de Chambly  Unibroue Dieu du ciel Molson ou Les 3 Brasseurs_?',
      '3. De quel gout particulier se rapproche la Guinness_?',
      '4. Qu est ce que le houblon regulierement utilise dans la production de biere_?',
      '5. Cree en 1810 et accueillant aujourd hui plus de 6 millions d amateurs de bieres dans quelle ville se deroule l Oktoberfest_?',
    ],
    answers: ['', 'Non', 'Unibroue', 'Du cafe', 'Une plante', 'Munich'],
  },
  {
    timer: { seconds: 20 },
    title: 'Annee 1900',
    questions: [
      'Tu te mets combien en Annee 1900_?',
      '1. Jacques Cartier etait il mort en 1900_?',
      '2. En Chine la revolte des Boxers concerna t elle des chiens des sous vetements ou des hommes_?',
      '3. Qui de Jacques Prevert Antoine de Saint Exupery ou Gaston Miron n est pas ne en 1900_?',
      '4. Quel territoire maritime est officiellement integre aux Etats Unis_? ',
      '5. Quelle importante institution financiere est fondee le 6 decembre a Levis en 1900_?',
    ],
    answers: [
      '',
      'Oui',
      'Des hommes precisement une societe secrete',
      'Gaston Miron',
      'Hawai',
      'Caisse Desjardins',
    ],
  },
  {
    timer: { seconds: 20 },
    title: 'Poutines',
    questions: [
      'Tu te mets combien en Poutines_?',
      '1. Nomme les trois ingredients classiques de la poutine.',
      '2. Va t on manger une poutine comme plkat principal comme accompagnement ou les deux_?',
      '3. Quels deux ingredients ajoute t on a ceux de base dans la poutique galvaude_?',
      '4. Combien de calories peut representer une portion normale de poutine classique_?',
      '5. Quelle grande chaine de restaurants americains fut la premiere a integrer la poutine dans son menu_?',
    ],
    answers: [
      '',
      'Frites sauce fromage en grains',
      'Les deux',
      'Poulet et petits pois verts',
      'Propositions entre 510 et 1110 calories acceptees',
      'Burger King en 1983',
    ],
  },
  {
    timer: { seconds: 20 },
    title: 'Chauves',
    questions: [
      'Tu te mets combien en Chauves_?',
      '1. Quel chauvre aide a nettoyer vos murs et vos planchers_?',
      '2. Quel chanteur country chauve et quebecois a longtemps porte une perruque frisee_?',
      '3. Lequel des humoristes suivants n est pas chauve  Martin Matte Martin Drainville ou Maxime Martin_?',
      '4. Quel chauve est devenu milliardaire grace au Cirque du Soleil_?',
      '5. Quel est le nom de famille du chef cuisinier Stefano_?',
    ],
    answers: [
      '',
      'Monsieur Net',
      'Patrick Normand',
      'Martin Drainville',
      'Guy Laliberte',
      'Faita',
    ],
  },
  {
    timer: { seconds: 20 },
    title: 'Animaux emblematiques',
    questions: [
      'Tu te mets combien en Animaux emblematiques_?',
      '1. Quel animal est l embleme du Canada  le castor la loutre la musaraigne ou le cyclope_?',
      '2. Julien Poulin pourrait etre bien familier avec cet animal qui est l embleme de Ferrari.',
      '3. A quel pays d Asie est habituellement associe le panda bien qu il s agisse d un embleme non officiel_?',
      '4. Quel est l animal emblematique de la Russie_?',
      '5. Le Portugal a le meme embleme qu un autre pays europeen lequel_?',
    ],
    answers: [
      '',
      'Le castor',
      'Le cheval',
      'La Chine',
      'L ours brun',
      'La France avec le coq comme embleme commun',
    ],
  },
  {
    timer: { seconds: 20 },
    title: 'Legumes',
    questions: [
      'Tu te mets combien en Legumes_?',
      '1. Une asperge est elle plutot ronde ovale ou longiligne_?',
      '2. Donne 3 des 6 couleurs possiblesw des poivrons.',
      '3. Lequel n est pas un synonyme de chou frise  chou kale chou plume chou romanesco ou chou frange_?',
      '4. Parmi les legumes suivants lequel contient le taux de fer le plus eleve  haricots blancs epinards lentilles ou salsifis_?',
      '5. Quel legume est le bouton d une fleur de plante potagere de la famille du chardon_?',
    ],
    answers: [
      '',
      'Longiligne',
      'Vert jaune rouge orange blanc noir violet ou mauve',
      'Chou romanesco',
      'Les lentilles avec 8.0 mg 100g haricots 7.0 salsifis 3.3 et epinards 2.7',
      'L artichaut',
    ],
  },
  {
    timer: { seconds: 20 },
    title: 'Acronymes quebecois',
    questions: [
      'Tu te mets combien en Acronymes quebecois_?',
      '1. CAQ signifie t il Cohabitation des Autochtones Quintuples Coalition Avenir Quebec ou Cooperative des Artisans du Qatar_?',
      '2. Ils ont pour mandat de faire le commerce des boissons alcoolisees sur tout le territoire du Quebec. Quel est leur acronyme_?',
      '3. Quel acronyme est utilise par le plus gros telediffuseur prive du Quebec_?',
      '4. Que signifie les lettres CLSC_?',
      '5. Que signifie les lettres CEGEP_?',
    ],
    answers: [
      '',
      'Coalition Avenir Quebec',
      'SAQ',
      'TVA',
      'Centre Local de Sante Communautaire',
      'Centre d Enseignement General Et Professionnel',
    ],
  },
  {
    timer: { seconds: 20 },
    title: 'Anatomie humaine',
    questions: [
      'Tu te mets combien en Anatomie humaine_?',
      '1. Chez l homme les testicules se situent ils au dessus du nez de l oreille ou de la cuisse_?',
      '2. Comment s appellent les dents qui se situent a cote de incisives_?',
      '3. Combien de muscles triceps le corps comprend il_?',
      '4. Cite les deux grands os situes sous le genou gauche_?',
      '5. Combien de vertebres composent la colonne vertebrale_?',
    ],
    answers: [
      '',
      'La cuisse si vous etes un homme et donnez une autre reponse prenez rendez vous d urgence chez un medecin generaliste.',
      'Les canines',
      '4 1 par bras et 1 par jambe',
      'Le tibia et la fibula ou perone',
      '33 ou 34 selon les personnes une des deux reponses acceptees',
    ],
  },
  {
    timer: { seconds: 20 },
    title: 'Cantons de l Est',
    questions: [
      'Tu te mets combien en Cantons de l Est_?',
      '1. Nommez la province qui etait autrefois connue sous le nom de Cantons de l Ouest par opposition aux Cantons de l Est.',
      '2. Quelle est la capitale regionale des Cantons de l Est_?',
      '3. Ne a Valcourt cet inventeur estrien est a l origine de l industrie de la motoneige et fonda un entreprise de calibre international portant son nom. Qui est ce_?',
      '4. On y trouve une cremerie dont les produits tres populaires portent le nom de la ville. Quelle est cette municipalite estrienne_?',
      '5. Combien de vignobles estiens sont officiellement inscrits sur La Route des Vins a 3 pres_?',
    ],
    answers: [
      '',
      'Ontario',
      'Sherbrooke',
      'Joseph Armand Bombardier',
      'Coaticook',
      '22',
    ],
  },
  {
    timer: { seconds: 20 },
    title: 'Litterature quebecoise',
    questions: [
      'Tu te mets combien en Litterature quebecoise_?',
      '1. Quel genre litteraire est generalement associe a Emilie Nelligan  roman poesie ou theatre_?',
      '2. A quel celebre roman de Claude Henri Grignon associes tu les personnages de Seraphin Poudrier Donalda Laloge et Alexis Labranche_?',
      '3. Laquelle de ces ecrivaines quebecoises est la premiere a avoir ete publiee  Christine Brouillette Gabrielle Roy Marie Laberge Kim Thuy_?',
      '4. Haitien d origine Quebecois d adoption il est le premier ecrivain du Quebec a faire partie de la prestigieuse Academie francaise. Qui est ce_?',
      '5. Cette trilogie d Arlette Cousture parle de trois generations de femmes de meme famille  Emilie Blanche et Elise. Quel en est le titre_?',
    ],
    answers: [
      '',
      'Poesie',
      'Une homme et son peche',
      'Gabrielle Roy',
      'Dany Laferriere',
      'Les filles de Caleb',
    ],
  },
  {
    timer: { seconds: 20 },
    title: 'Villes quebecoises',
    questions: [
      'Tu te mets combien en Villes quebecoises_?',
      '1. Quelle ville est la capitale du Quebec_? ',
      '2. Quelle ville est la plus peuplee du Quebec_?',
      '3. Dans quelle ville trouve t on le plus grand jardin zoologique de la province_?',
      '4. Quelle ville fut victime de l explosion d un train faisant 47 morts le 6 juillet 2013_?',
      '5. Laquelle des villes suivantes est la plus ancienne  Trois Rivieres Rimouski Chambly ou Vercheres_?',
    ],
    answers: [
      '',
      'Quebec',
      'Montreal',
      'Granby',
      'Lac Megantic',
      'Trois Rivieres 1634',
    ],
  },
  {
    timer: { seconds: 20 },
    title: 'Jean de la Fontaine',
    questions: [
      'Tu te mets combien en Jean de la Fontaine_?',
      '1. Ecrire des fables faisait il de lui un fabuleux un fabuliste ou un faberge_?',
      '2. Que tenait dans son bec le corbeau dans Le Corbeau et le renard_?',
      '3. Laquelle de ces fabres n existe pas  La cigale et la fourmi Le singe et le chat Le heron et la truite_?',
      '4. Quelle est la morale de la fable Le lievre et la tortue_?',
      '5. De quelle oeuvre dont le titre associe 2 animaux est tiree la phrase On a souvent besoin d un plus petit que soi_?',
    ],
    answers: [
      '',
      'Un fabuliste',
      'Un fromage',
      'Le heron et la truite',
      'Rien ne sert de courir il faut partir a point',
      'Le lion et le rat ou La colombe et la fourmi',
    ],
  },
  {
    timer: { seconds: 20 },
    title: 'Series televisees quebecoises',
    questions: [
      'Tu te mets combien en Series televisees quebecoises_?',
      '1. Guy A. Lepage y jouait le role du gars et Sylvie Leonard y jouait le role de la fille. Comment s appelait cette serie_?',
      '2. L action d Unite 9 se deroule principalement ou  un hopital un restaurant une prison ou un bar_?',
      '3. Quel humoriste est la vedette de Les Beaux Malaises_?',
      '4. Completez le surnom de ce personnage rendu celebre par la serie Les Invincibles  Lyne .....',
      '5. Qui jouait les roles de Pete et Lola dans Chambres en Ville_?',
    ],
    answers: [
      '',
      'Un gars une fille',
      'Une prison',
      'Martin Matte',
      'Le pas fine',
      'Francis Reddy et Anne Dorval',
    ],
  },
  {
    timer: { seconds: 20 },
    title: 'Humoristes quebecois',
    questions: [
      'Tu te mets combien en Humoristes quebecois_?',
      '1. Qui disait toujours que ce serait son dernier Bye Bye_?',
      '2. En l honneur de quel defunt humoriste le gala des Oliviers fut il nomme_?',
      '3. Quel humoriste fut un pionnier en ayant initie la pratique du stand up au Quebec avec son monologue Les unions quoss a donne_?',
      '4. Quel duo d humoristes fut connu pour ses vestons a tache de vache_?',
      '5. Qui est la marionnette de femme d age mure qui a souvent fait partie des spectacles de Stephane Rousseau_?',
    ],
    answers: [
      '',
      'Dominique Michel',
      'Olivier Guimond',
      'Yvon Deschamps',
      'Ding et Dong Claude Meunier et Serge Theriault',
      'Madame Jigger',
    ],
  },
  {
    timer: { seconds: 20 },
    title: 'Canadiens de Montreal',
    questions: [
      'Tu te mets combien en Canadiens de Montreal_?',
      '1. La superstar des Canadiens au debut des annees 1990 s appelait elle Patrick Baron Patrick Leduc ou Patrick Roy_?',
      '2. Avant d accueillir leurs adversaires au Centre Bell a quel endroit les Canadiens les recevaient ils jusqu en mars 1996_?',
      '3. Qui est le plus grand marqueur de l histoire des Canadiens_?',
      '4. En date de 2019 combien de fois ont ils gagne la Coupe Stanley_?',
      '5. Qui est le joueur ayant recolte le plus grand nombre de punitions de son histoire_?',
    ],
    answers: [
      '',
      'Patrick Roy',
      'Au Forum de Montreal',
      'Maurice Richard 544 buts',
      '24 fois',
      'Chris Nilan 2248 fois',
    ],
  },
  {
    timer: { seconds: 20 },
    title: 'Passe Partout',
    questions: [
      'Tu te mets combien en Passe Partout_?',
      '1. Dans quelle langue l emission est elle presentee_?',
      '2. Qui sont les deux autres personnages principaux accompagnant Passe Partout dans chaque emission_?',
      '3. Quel ami de Passe Partout habite sur une ferme_?',
      '4. Qui est la voisine de Prunau et Cannelle_?',
      '5. Quel animal represente le toutou de Cannelle_? ',
    ],
    answers: [
      '',
      'Francais',
      'Passe Carreau et Passe Montagne',
      'Fardoche',
      'Mme Coucou',
      'Un phoque',
    ],
  },
  {
    timer: { seconds: 20 },
    title: 'Pizzas',
    questions: [
      'Tu te mets combien en Pizzas_?',
      '1. Quel est l ingredient indispensable que l on retrouve dans une pizza indice  mozzarella gorgonzola gruyere parmesan_?',
      '2. Quel fruit est agilement pose sur une pizza hawaienne_?',
      '3. Si vous faites une pizza blanche quel ingredient classique sera absent_?',
      '4. Nommez les trois garnitures traditionnelles d une pizza Margheritta.',
      '5. Si vous etes au Pizza Hut a Montreal outre la sauce et le fromage quels seront les trois ingredients d une pizza quebecoise sur le menu_?',
    ],
    answers: [
      '',
      'Le fromage',
      'L ananas',
      'Les tomates',
      'Tomates mozarella basilic',
      'Pepperoni champignons bacon',
    ],
  },
  {
    timer: { seconds: 20 },
    title: 'La Guerre des Tuques',
    questions: [
      'Tu te mets combien en La Guerre des Tuques_?',
      '1. Durant quelle saison prend place l action du film_?',
      '2. Comment s appelait le chien du film  Fido Rex Medor ou Cleo_?',
      '3. En quoi la nouvelle version du film de 2015 est elle differente de la premiere_?',
      '4. La Guerre des Tuques est le numero 1 d une serie de plus de 20 films dedies a un public familial. Comment se nomme cette serie_?',
      '5. En quelle annee fut realise le film a 2 ans pres_?',
    ],
    answers: [
      '',
      'L hiver',
      'Cleo',
      'C est un film anime en 3D',
      'Contes pour tous',
      '1984',
    ],
  },
];
